// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anmkrrboofzijanebbla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFubWtycmJvb2Z6aWphbmViYmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMTg2NDgsImV4cCI6MjA1MTg5NDY0OH0.hory8ODIVjyaG70_Exhu31UUML3vuLPDUO-QcDIZPfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);